# Generated by Django 2.1.1 on 2018-12-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=124)),
                ('description', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('co', 'Completed'), ('de', 'Deleted'), ('ip', 'In progress')], default='ip', max_length=2)),
            ],
        ),
    ]
